# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64aa6037c917a9c0c3938f8027fe859acef5c7476a5e5b38912cbb35f40e0452000f97019e35da4d1ef46cf58a28c337ed6b762d795e9bc8351bae40c0096a6b

test:
  secret_key_base: 05ea1ce3092ce52eb2ea4451567a67c6118b8cb7f3d3fc7c9273de123fa38576a826b76d40ebe93980e13d5edaf02a13b91a11e17056304a9fdbb175dac05ec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
